### ISSUE TITLE
Serialize return different values depending of the OS

### ISSUE THREAD

**Issue by eduardocodengage** [Codibre/multi-serializer#21] opened 2021-10-25 20:51 UTC
Using the code below is returning different values on linux and windows

Windows = H4sIAAAAAAAACouOBQApu0wNAgAAAA==
Linux = H4sIAAAAAAAAA4uOBQApu0wNAgAAAA==

```
import { Base64Strategy, GzipStrategy, JsonStrategy, Serializer } from 'multi-serializer';

const convert = new Serializer( new JsonStrategy(), new GzipStrategy(), new Base64Strategy() );

convert.serialize([]).then(data => console.log(data));
```

**Comment by eduardocodengage** [comment] 2021-10-25 20:52
This is just a example with [], but using full data it's returning different values too

**Comment by Farenheith** [comment] 2021-10-26 01:35
Thanks for the report! I'll look into that

**Comment by Farenheith** [comment] 2021-10-26 01:54
Looks like both strings can be decompressed in Linux:

```ts
  it('should decompress a Linux generated empty array gzip result', async () => {
    const serializer = new Serializer( new JsonStrategy(), new GzipStrategy(), new Base64Strategy() );

    const result = await serializer.deserialize('H4sIAAAAAAAACouOBQApu0wNAgAAAA==');

    expect(result).toEqual([]);
  });

  it('should decompress a Windows generated empty array gzip result', async () => {
    const serializer = new Serializer( new JsonStrategy(), new GzipStrategy(), new Base64Strategy() );

    const result = await serializer.deserialize('H4sIAAAAAAAAA4uOBQApu0wNAgAAAA==');

    expect(result).toEqual([]);
  });
``` 

Also, looks like this is expected behavior. In the gzip specification, there's one byte that refers to the OS system where the data was compressed:

```ts
         +---+---+---+---+---+---+---+---+---+---+
         |ID1|ID2|CM |FLG|     MTIME     |XFL|OS | (more-->)
         +---+---+---+---+---+---+---+---+---+---+
```
The possible values for the byte **OS** are:
```
                 0 - FAT filesystem (MS-DOS, OS/2, NT/Win32)
                 1 - Amiga
                 2 - VMS (or OpenVMS)
                 3 - Unix
                 4 - VM/CMS
                 5 - Atari TOS
                 6 - HPFS filesystem (OS/2, NT)
                 7 - Macintosh
                 8 - Z-System
                 9 - CP/M
                10 - TOPS-20
                11 - NTFS filesystem (NT)
                12 - QDOS
                13 - Acorn RISCOS
               255 - unknown
```

You can find out more here: https://datatracker.ietf.org/doc/html/rfc1952#page-6

**Comment by Farenheith** [comment] 2021-10-26 01:56
I'll close this issue. If you experience any further problems with some cross-os decompression you can comment here and I look on it again

**Closed as completed by Farenheith** 2021-10-26 01:56 UTC
